controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Response;
use app\models\Event;
use yii\web\Controller;
use app\models\Platform;
use yii\data\Pagination;
use app\models\LoginForm;
use app\models\SignupForm;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     * list of nearest events
     * @return string
     */
    public function actionIndex()
    {
        $query = Event::find()
            ->leftJoin('platform', 'platform.id= platform_id')
            ->where('date > :date AND  platform.status = :status',
                [
                    ':date' => date("Y-m-d H:i:s"),
                    ':status' => Platform::STATUS_ACTIVE
                ])
            ->orderBy('date');
        $countQuery = clone $query;
        $pagination = new Pagination(['totalCount' => $countQuery->count(), 'pageSize' => 6]);
        $events = $query->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('index', [
            'events' => $events,
            'pagination' => $pagination,
        ]);


        return $this->render('index');
    }

    /**
     * Displays platform list page.
     *
     * @return Response|string
     */

    public function actionPlatform()
    {
        $query = Platform::find()->where('status = :status', ['status' => Platform::STATUS_ACTIVE])->orderBy('sort');
        $countQuery = clone $query;
        $pagination = new Pagination(['totalCount' => $countQuery->count(), 'pageSize' => 4]);
        $platforms = $query->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('platform', [
            'platforms' => $platforms,
            'pagination' => $pagination,
        ]);

    }

    /**
     * Displays event list page.
     *
     * @return Response|string
     */

    public function actionEvent($id)
    {
        if (!$id) {
            return $this->redirect('/site/index');
        }

        $platform = Platform::findOne($id);

        if ($platform->status == Platform::STATUS_NOT_ACTIVE) {
            return $this->redirect('/site/index');
        }

        $query = Event::find()->where('platform_id = :platform_id', [':platform_id' => (int)$id]);
        $countQuery = clone $query;
        $pagination = new Pagination(['totalCount' => $countQuery->count(), 'pageSize' => 4]);
        $events = $query->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('event', [
            'platform' => $platform,
            'events' => $events,
            'pagination' => $pagination,
        ]);
    }

    /**
     * Displays show page.
     *
     * @return Response|string
     */

    public function actionShow($id)
    {
        if (!$id) {
            return $this->redirect('/site/index');
        }
        $event = Event::findOne($id);
        return $this->render('show', [
            'event' => $event,
        ]);

    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays signup page.
     *
     * @return Response|string
     */

    public function actionSignup()
    {
        $model = new SignupForm();

        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /*    public function actionAddAdmin() {
            $model = User::find()->where(['username' => 'admin'])->one();
            if (empty($model)) {
                $user = new User();
                $user->username = 'admin';
                $user->email = 'admin@test.com';
                $user->setPassword('admin');
                $user->generateAuthKey();
                if ($user->save()) {
                    echo 'good';
                }
            }
        }*/
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */

/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/event.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\LinkPager;

/* @var $this yii\web\View */
/* @var $searchModel app\models\EventSerch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Events';
$this->params['breadcrumbs'][] = ['label' => $platform->title, 'url' => ['/site/platform']];
$this->params['breadcrumbs'][] = $this->title;


?>
<div class="platform-view">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <img class="img-responsive" src="<?= $platform->getImage(); ?>">
            </div>
        </div>
        <div class="col-md-4">
            <div class="">
                <h4><a href="#"><?= $platform->title; ?></a></h4>
                <p><?= $platform->description; ?></p>
            </div>
        </div>
    </div>
</div>

<div class="event-view">
    <h1>События</h1>
    <?php if ($events): ?>
        <div class="row">
            <?php foreach ($events as $event): ?>
                <div class="col-md-4">
                    <div class="card h-100">
                        <img class="img-responsive" src="<?= $event->show->getImage(); ?>">
                        <div class="card-body">
                            <h4>
                                <a href="<?= Url::toRoute(['/site/show', 'id' => $event->id]) ?>"><?= $event->show->title; ?></a>
                            </h4>
                            <p>Дата события: <?= $event->date; ?></p>
                            <p>Площадка: <a
                                        href="<?= Url::toRoute(['/site/event', 'id' => $event->platform->id]) ?>"><?= $event->platform->title; ?></a>
                            </p>
                            <p><?= $event->show->short_description; ?></p>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php
        echo LinkPager::widget([
            'pagination' => $pagination,
        ]);
        ?>
    <?php else: ?>
        <div class="row">
            <div class="col-md-12"><p>События не найдены</p></div>
        </div>
    <?php endif; ?>
</div>

views/site/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\LinkPager;

/* @var $this yii\web\View */

$this->title = 'Список ближайших событий';
?>
<div class="index">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
        <?php foreach ($events as $event): ?>
            <div class="col-md-4">
                <div class="card h-100">
                    <img class="img-responsive" src="<?= $event->show->getImage(); ?>">
                    <div class="card-body">
                        <h4>
                            <a href="<?= Url::toRoute(['/site/show', 'id' => $event->id]) ?>"><?= $event->show->title; ?></a>
                        </h4>
                        <p>Дата события: <?= $event->date; ?></p>
                        <p>Площадка: <a
                                    href="<?= Url::toRoute(['/site/event', 'id' => $event->platform->id]) ?>"><?= $event->platform->title; ?></a>
                        </p>
                        <p><?= $event->show->short_description; ?></p>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <?php
    echo LinkPager::widget([
        'pagination' => $pagination,
    ]);
    ?>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'rememberMe')->checkbox([
        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
    ]) ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/platform.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\LinkPager;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PlatformSerch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Площадки';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="platform-index">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
        <?php foreach ($platforms as $platform): ?>
            <div class="col-md-3">
                <div class="card h-100">
                    <img class="img-responsive" src="<?= $platform->getImage(); ?>">
                    <div class="card-body">
                        <h4><?= $platform->title; ?></h4>
                        <p><?= $platform->short_description; ?></p>
                    </div>
                    <div class="card-footer">
                        <a href="<?= Url::toRoute(['/site/event', 'id' => $platform->id]) ?>" class="btn btn-primary">События
                            площадки</a>
                    </div>

                </div>

            </div>
        <?php endforeach; ?>
    </div>
    <?php
    echo LinkPager::widget([
        'pagination' => $pagination,
    ]);
    ?>
</div>

views/site/show.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ShowSerch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Shows';

$this->params['breadcrumbs'][] = ['label' => $event->platform->title, 'url' => ['/site/event?id=' . $event->platform->id]];
$this->params['breadcrumbs'][] = ['label' => $event->title, 'url' => ['/site/event?id=' . $event->platform->id]];
$this->params['breadcrumbs'][] = $this->title;
?>

<?php if ($event): ?>
    <div class="event-view">
        <h1><?= $event->show->title ?></h1>
        <div class="row">
            <div class="col-md-12">
                <div class="">
                    <img class="img-responsive" src="<?= $event->show->getImage(); ?>">
                    <div class="card-body">
                        <h4><a href="#"><?= $event->show->title; ?></a></h4>
                        <p>Дата события: <?= $event->date; ?></p>
                        <p>Площадка: <a
                                    href="<?= Url::toRoute(['/site/event', 'id' => $event->platform->id]) ?>"><?= $event->platform->title; ?></a>
                        </p>
                        <p><?= $event->show->description; ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>

views/site/signup.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>Please fill out the following fields to signup:</p>
    <div class="row">
        <div class="col-lg-5">

            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
            <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>
            <?= $form->field($model, 'email') ?>
            <?= $form->field($model, 'password')->passwordInput() ?>
            <div class="form-group">
                <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
            </div>
            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>